# ---qsub parameter settings---
# --these can be overrode at qsub invocation--

# tell sge to execute in bash
#$ -S /bin/bash

# tell sge to submit any of these queue when available
#$ -q cgc.q

# tell sge that you are in the users current working directory
#$ -cwd

# tell sge to export the users environment variables
#$ -V

# tell sge to submit at this priority setting
#$ -p -10

# tell sge to output both stderr and stdout to the same file
#$ -j y

# export all variables, useful to find out what compute node the program was executed on
# redirecting stderr/stdout to file as a log.

set

echo

JAVA_1_8=$1
GATK_DIR=$2
CORE_PATH=$3

PROJECT=$4
FAMILY=$5
REF_GENOME=$6
CHROMOSOME=$7

# Filter to just on all of the variants all

START_GATHER_FAMILY_ON_TARGET=`date '+%s'`

$JAVA_1_8/java -cp $GATK_DIR/GenomeAnalysisTK.jar \
org.broadinstitute.gatk.tools.CatVariants \
-R $REF_GENOME \
--assumeSorted \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.1.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.2.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.3.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.4.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.5.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.6.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.7.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.8.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.9.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.10.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.11.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.12.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.13.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.14.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.15.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.16.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.17.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.18.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.19.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.20.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.21.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.22.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.X.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.Y.vcf" \
--outputFile $CORE_PATH/$PROJECT/$FAMILY/VCF/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.vcf"

END_GATHER_FAMILY_ON_TARGET=`date '+%s'`

HOSTNAME=`hostname`

echo $FAMILY"_"$PROJECT",T.01,GATHER_FAMILY_ON_TARGET_"$CHROMOSOME"_VCF,"$HOSTNAME","$START_GATHER_FAMILY_ON_TARGET","$END_GATHER_FAMILY_ON_TARGET \
>> $CORE_PATH/$PROJECT/REPORTS/$PROJECT".WALL.CLOCK.TIMES.csv"

echo $JAVA_1_8/java -cp $GATK_DIR/GenomeAnalysisTK.jar \
org.broadinstitute.gatk.tools.CatVariants \
-R $REF_GENOME \
--assumeSorted \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.1.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.2.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.3.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.4.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.5.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.6.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.7.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.8.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.9.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.10.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.11.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.12.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.13.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.14.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.15.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.16.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.17.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.18.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.19.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.20.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.21.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.22.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.X.vcf" \
--variant $CORE_PATH/$PROJECT/TEMP/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.Y.vcf" \
--outputFile $CORE_PATH/$PROJECT/$FAMILY/VCF/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.vcf" \
>> $CORE_PATH/$PROJECT/$FAMILY/$FAMILY".COMMAND.LINES.txt"

echo >> $CORE_PATH/$PROJECT/$FAMILY/$FAMILY".COMMAND.LINES.txt"

md5sum $CORE_PATH/$PROJECT/$FAMILY/VCF/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.vcf.gz" \
>> $CORE_PATH/$PROJECT/REPORTS/$PROJECT".CIDR.Analysis.MD5.txt"

md5sum $CORE_PATH/$PROJECT/$FAMILY/VCF/$FAMILY".VQSR.ANNOTATED.JUST_FAMILY.ON_TARGET.VARIANT_ONLY.vcf.gz.tbi" \
>> $CORE_PATH/$PROJECT/REPORTS/$PROJECT".CIDR.Analysis.MD5.txt"
